---
functional: 
  - Сайт должен быть доступен на различных устройствах
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины 
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
non-functional: 
  - Сайт должен быть безопасным и защищать данные пользователя
implicit: 
  - Необходимо добавить на сайт возможность сброса фильтра по товарам
  - Возможность настройки фильтра цены по максимальной цене до 10000,00
  - Сделать соответствие между фильтрами "категория" и "бренд"
